### ISSUE TITLE
Resistance read throws error on output

### ISSUE THREAD

**Issue by dmlewis9** [edges-collab/edges-io#21]
https://github.com/edges-collab/edges-io/blob/c9ec9a315ffe31e36e11be9f1fa69ff6b6c9b195/src/edges_io/io.py#L629-L660

It seems that the change in dtype for the resistance read() function is breaking it, resulting in too many indices.

**Comment by dmlewis9** [comment]
Fixed with https://github.com/edges-collab/edges-io/commit/1c3716cc8c200f2e26688a4dcd13d59f2b7313ec

Note that the current version of this makes the data and metadata the same array. We will probably want to cut down the metadata in the future.

**Comment by steven-murray** [comment]
I'm not sure: for resistance readings, what is the "metadata" as opposed to data? Reading it all into one key-searchable array means we can use any of it later on in analysis. I don't think the resistance data is too big either.
