### ISSUE TITLE
Read in frequencies

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-io#4]
At the moment, frequencies are not read in from spectrum files (or any file). They should be.

**Comment by dmlewis9** [comment]
Threw up a pass at this. Running read_all() for an observation should now generate frequency arrays for each spectra, from 0 to 200 MHz, based on the power array size.

**Comment by dmlewis9** [comment]
https://github.com/edges-collab/edges-io/commit/3d559a1925444c3afbff6e9a5dc521eb4dcdda1e now reads in frequencies using the metadata, replacing the method above.

**Comment by steven-murray** [comment]
Fixed by #18
