### ISSUE TITLE
Full metadata

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-io#8]
Any metadata of any of the associated formats should be readable and saved to the class. Linked to #7 and #4 .

**Comment by dmlewis9** [comment]
https://github.com/edges-collab/edges-io/commit/be80ea3d00f2c70d03944e0d80df91e206668364 adds in the ability to read metadata from read_acq, uses it to generate frequencies from #4.

**Comment by dmlewis9** [comment]
https://github.com/edges-collab/edges-io/commit/3d559a1925444c3afbff6e9a5dc521eb4dcdda1e does the full metadata properly on file read for both acq and h5 files.

**Comment by steven-murray** [comment]
Fixed by #18
